### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by RollerIn** [Arjun-Ar91/WebdriverIO6-appium-cucumber-boilerplate#11]
While resolving: WebdriverIO6-appium-cucumber-boilerplate@1.0.0
npm ERR! Found: @wdio/cucumber-framework@7.9.1
npm ERR! node_modules/@wdio/cucumber-framework
npm ERR!   dev @wdio/cucumber-framework@"^7.9.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cucumber-framework@"~7.7.3" from wdio-cucumberjs-json-reporter@4.0.0

**Comment by sarahmadhani** [comment]
while run npn run ..
[0-0] 2021-08-24T14:09:36.175Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
[0-0] 2021-08-24T14:09:36.176Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
    at getErrorFromResponseBody (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/webdriver/build/utils.js:121:10)
    at WebDriverRequest._request (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/webdriver/build/request.js:148:56)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async startWebDriverSession (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/webdriver/build/utils.js:41:16)
    at async Function.newSession (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/webdriver/build/index.js:44:23)
    at async remote (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/webdriverio/build/index.js:66:20)
    at async Runner._startSession (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/runner/build/index.js:206:50)
    at async Runner._initSession (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/runner/build/index.js:175:21)
    at async Runner.run (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/runner/build/index.js:93:15)
[0-0] 2021-08-24T14:09:36.177Z ERROR @wdio/runner: Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
    at startWebDriverSession (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/webdriver/build/utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.newSession (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/webdriver/build/index.js:44:23)
    at async remote (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/webdriverio/build/index.js:66:20)
    at async Runner._startSession (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/runner/build/index.js:206:50)
    at async Runner._initSession (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/runner/build/index.js:175:21)
    at async Runner.run (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/runner/build/index.js:93:15)
[0-0]  Error:  Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
[0-0] FAILED in /home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/apps/Celsius Fahrenheit Converter_v1.0.1_apkpure.com.apk - /src/featureFiles/sampleTest.feature
2021-08-24T14:09:36.301Z INFO @wdio/cli:launcher: Run onComplete hook
2021-08-24T14:09:36.308Z ERROR @wdio/cli:utils: Error in onCompleteHook: Error: There were issues reading JSON-files from './reports/json'.
    at collectJSONS (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:16:15)
    at generateReport (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:69:22)
    at Object.onComplete (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/config/wdio.conf.js:269:9)
    at /home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/cli/build/utils.js:82:13
    at Array.map (<anonymous>)
    at runOnCompleteHook (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/cli/build/utils.js:80:37)
    at Launcher.run (/home/sarah/Documents/WebdriverIO-V6-appium-cucumber-boilerplate/node_modules/@wdio/cli/build/launcher.js:83:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by Arjun-Ar91** [comment]
@sarahmadhani You need to setup android studio/sdk setup for appium to run.
